### ISSUE TITLE
First Integration Task List

### ISSUE THREAD

**Issue by FMCalisto** [MIMBCD-UI/prototype-breast-screening#52]
The next tasks are related to the following projects: (i) [dicom-converter](https://github.com/MIMBCD-UI/dicom-converter); (ii) [dicom-anonymizer](https://github.com/MIMBCD-UI/dicom-anonymizer); (iii) [dataset-manager](https://github.com/MIMBCD-UI/dataset-manager); and (iv) [dicom-organizer](https://github.com/MIMBCD-UI/dicom-organizer). These projects will promote the v1.0.6-alpha version, known as the first integration version.

## Task List

- [x] 1. DICOM Image Converter Refactor #41

- [x] 2. DICOM Image Anonymizer Development #42

- [x] 2.1. Anonymize Patient's Name #43

- [x] 2.2. Anonymize Doctor's Name #44

- [x] 3. Dataset Manager #45

- [x] 3.1. Reference Query #46

- [x] 3.2. Reference Reader #47

- [x] 3.3. MAT Files Generator #48

- [x] 4. DICOM Image Organizer #49

- [x] 4.1. DICOM Reader #50

- [x] 4.2. DICOM Writer #51
