### ISSUE TITLE
New Features List

### ISSUE THREAD

**Issue by FMCalisto** [MIMBCD-UI/prototype-breast-screening#78]
List of new features from post-testing phases:

#### Multi-Modality Image Annotator

- [x] Bullet Size #74

- [x] Close Annotations Colour #86

- [x] Preliminary Log In System #76

- [x] Loading #75

- [x] Saving Methods #70

- [x] Fix: Image Counter #67

- [x] Change Tag #71

- [x] Zoom & Pan Interaction Technique #79

- [x] Delete Last Annotation Improvement #80

#### Multi-Classifier System

- [x] Clinical Covariates #77

- [x] Breast Densities Classifier #81

- [x] BIRADS Classifier #82

- [x] Phathology Option #95
